local reinforcementDefs = {
["ger"] = {
	["gertrucksupplies"] = 3,
	["gerflak38_stationary"] = 4,
	["gerrifle"] = 50,
	["gertiger"] = 5,
	["gertigerii"] = 2,
	["gerpanther"] = 6,
	["gersdkfz251"] = 10,
	["gersdkfz250"] = 6,
	["gerstugiii"] = 6,
	["gerpuma"] = 12,
	},
["rus"] = {
	["rustrucksupplies"] = 3,
	["rus61k_stationary"] = 4,
	["rusrifle"] = 100,
	["rusppsh"] = 50,
	["rust60"] = 15,
	["rusm5halftrack"] = 5,
	["rust3485"] = 6,
	["rusis2"] = 2,
	["rusisu152"] = 4,
	["rusbm13n"] = 2,
	["rusba64"] = 10,
	},
["us"] = {
	["ustrucksupplies"] = 3,
	["usm1bofors_stationary"] = 4,
	["usgirifle"] = 60,
	["usgibar"] = 30,
	["usgithompson"] = 30,
	["usgiflamethrower"] = 15,
	["usm5stuart"] = 20,
	["usm3halftrack"] = 10,
	["usm8greyhound"] = 8,
	["usm4a4sherman"] = 12,
	["usm4a3105sherman"] = 4,
	},
["gbr"] = {
	["gbrtrucksupplies"] = 3,
	["gbrbofors_stationary"] = 4,
	["gbrrifle"] = 50,
	["gbrsten"] = 30,
	["gbrcommando"] = 20,
	["gbrwasp"] = 20,
	["gbrm5halftrack"] = 10,
	["gbrcromwell"] = 8,
	["gbraecmkii"] = 10,
	["gbrcromwellmkvi"] = 4,
	["gbrchurchillmkvii"] = 4,
	},
["zom"] = {
	["zomsprinter"] = 250
	},
}
return reinforcementDefs